/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-TWAIN.h
 #	source generated by 4D Plugin Wizard
 #	Project : TWAIN
 #	author : miyako
 #	2019/09/26
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_TWAIN_H
#define PLUGIN_TWAIN_H

#include "4DPluginAPI.h"

#include "4DPlugin-JSON.h"

#include "twain_jpg.h"
#include "twain_png.h"
#include "twain_dsm.h"

#include "json.h"

typedef struct
{
    TW_UINT16 majorNum;
    TW_UINT16 minorNum;
    TW_UINT16 language;
    TW_UINT16 country;
    TW_UINT16 format;
}twain_version_info_t;

#include "C_TEXT.h"

#if VERSIONMAC
#include <sstream>
#endif

#pragma mark -

void TWAIN_Get_devices(PA_PluginParameters params);
void TWAIN_Get_default_option(PA_PluginParameters params);
void TWAIN_SCAN(PA_PluginParameters params);

#if VERSIONWIN
unsigned __stdcall doScanWin(void *p);
unsigned __stdcall getOptionWin(void *p);
#endif

void doScan(C_TEXT &Param1_scanner,
            CUTF8String& Param2_option,
            std::vector<uint8_t>& data,
            TW_UINT16 majorNum,
            TW_UINT16 minorNum,
            TW_UINT16 language,
            TW_UINT16 country,
            int Param3_format);

void getOption(
               C_TEXT& Param1_scanner,
	CUTF8String& Param2_option,
               std::vector<uint8_t>& data,
               TW_UINT16 majorNum,
               TW_UINT16 minorNum,
               TW_UINT16 language,
               TW_UINT16 country);

/* thread stuff */

#if VERSIONWIN
HANDLE createFmIn1(C_TEXT& Param1_scanner,
	CUTF8String& Param2_option,
	std::wstring& ParamA,
	std::wstring& ParamB,
	DWORD *ParamA_len,
	DWORD *ParamB_len,
	DWORD *Param1_len,
	DWORD *Param2_len);

HANDLE createFmIn2(DWORD *ParamA_len,
	DWORD *ParamB_len,
	DWORD *Param1_len,
	DWORD *Param2_len);

HANDLE createEventforBufIn2(LPVOID bufIn,
	DWORD ParamA_len,
	DWORD ParamB_len,
	DWORD Param1_len,
	DWORD Param2_len,
	std::wstring& ParamA,
	std::wstring& ParamB,
	C_TEXT& Param1_scanner,
	CUTF8String& Param2_option);

HANDLE createFmOut2(std::vector<uint8_t>& data);
void getDataFromThread2(std::vector<uint8_t>& data);
void waitForEvent(HANDLE h, HANDLE scanEvent_p, std::vector<uint8_t>& data, std::wstring& ParamB, DWORD len);
#endif

#endif /* PLUGIN_TWAIN_H */
